### ISSUE TITLE
Users with ADMFLAG_GENERIC don't get any message on connect

### ISSUE THREAD

**Issue by KewaiiGamer** [hallucinogenic/HUD-Text-Connect-Message#2]
https://github.com/hallucinogenic/New-Hud-Connect-Message/blob/b3e0c0dd0602b373acde4c7eada3308b69319448/scripting/newhud_connectmessage.sp#L71-L74

As the title say when any user with ADMFLAG_GENERIC no message is displayed. I don't know if this behavior is intended but if it is then it shouldn't be.

I recommend setting a ConVar to disable if you think it might be useful!

**Comment by luis-rei97** [comment]
Fixed
