### ISSUE TITLE
ShowHudText should automatically select a channel

### ISSUE THREAD

**Issue by KewaiiGamer** [hallucinogenic/HUD-Text-Connect-Message#3]
https://github.com/hallucinogenic/New-Hud-Connect-Message/blob/b3e0c0dd0602b373acde4c7eada3308b69319448/scripting/newhud_connectmessage.sp#L122

The second argument should be "-1" instead of "5". That way when other plugins there is no issues with other addons!

**Comment by luis-rei97** [comment]
Fixed
